package clientgen

import (
	"bytes"
	"fmt"
	"sort"
	"strings"

	"pulse.dev/internal/wire"
	"pulse.dev/internal/wiremodel"
)

func (g *tsGenerator) render() ([]byte, error) {
	slug := strings.TrimSpace(g.opts.AppSlug)
	if slug == "" {
		slug = strings.TrimSpace(g.app.Name)
	}
	if slug == "" {
		slug = "pulse"
	}

	var buf bytes.Buffer
	buf.WriteString("// Code generated by Pulse. DO NOT EDIT.\n\n")
	buf.WriteString("/* eslint-disable */\n")
	buf.WriteString("/* jshint ignore:start */\n")
	buf.WriteString("/* jslint-disable */\n\n")
	buf.WriteString("export type BaseURL = string\n\n")
	buf.WriteString(`export const Local: BaseURL = "http://localhost:4000"` + "\n\n")
	buf.WriteString("export function Environment(name: string): BaseURL {\n")
	buf.WriteString(fmt.Sprintf("    return `https://${name}-%s.encr.app`\n", slug))
	buf.WriteString("}\n\n")
	buf.WriteString("export function PreviewEnv(pr: number | string): BaseURL {\n")
	buf.WriteString("    return Environment(`pr${pr}`)\n")
	buf.WriteString("}\n\n")
	buf.WriteString(`const BROWSER = typeof globalThis === "object" && ("window" in globalThis)` + "\n\n")
	capabilities := wiremodel.AppCapabilities(g.app)
	buf.WriteString(fmt.Sprintf("const PULSE_WIRE_SCHEMA_HASH = %q\n", capabilities.SchemaHash))
	buf.WriteString(fmt.Sprintf("const PULSE_WIRE_CONTENT_TYPE = %q\n\n", wire.ContentType))

	serviceNames := make([]string, 0, len(g.namespaces))
	serviceNames = append(serviceNames, namespaceNamesWithMethods(g.namespaces)...)
	sort.Strings(serviceNames)

	buf.WriteString("export default class Client {\n")
	for _, svcName := range serviceNames {
		buf.WriteString(fmt.Sprintf("    public readonly %s: %s.ServiceClient\n", svcName, svcName))
	}
	buf.WriteString("    private readonly options: ClientOptions\n")
	buf.WriteString("    private readonly target: string\n\n")
	buf.WriteString("    constructor(target: string, token?: string)\n")
	buf.WriteString("    constructor(target: BaseURL, options?: ClientOptions)\n")
	buf.WriteString(`    constructor(target: string | BaseURL = "prod", options?: string | ClientOptions) {` + "\n")
	buf.WriteString(`        if (!target.startsWith("http://") && !target.startsWith("https://")) {` + "\n")
	buf.WriteString("            target = Environment(target)\n")
	buf.WriteString("        }\n\n")
	buf.WriteString(`        if (typeof options === "string") {` + "\n")
	buf.WriteString("            options = { auth: options }\n")
	buf.WriteString("        }\n\n")
	buf.WriteString("        this.target = target\n")
	buf.WriteString("        this.options = options ?? {}\n")
	buf.WriteString("        const base = new BaseClient(this.target, this.options)\n")
	for _, svcName := range serviceNames {
		buf.WriteString(fmt.Sprintf("        this.%s = new %s.ServiceClient(base)\n", svcName, svcName))
	}
	buf.WriteString("    }\n\n")
	buf.WriteString("    public with(options: ClientOptions): Client {\n")
	buf.WriteString("        return new Client(this.target, {\n")
	buf.WriteString("            ...this.options,\n")
	buf.WriteString("            ...options,\n")
	buf.WriteString("        })\n")
	buf.WriteString("    }\n")
	buf.WriteString("}\n\n")

	buf.WriteString("export interface ClientOptions {\n")
	buf.WriteString("    fetcher?: Fetcher\n")
	buf.WriteString(`    requestInit?: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }` + "\n")
	buf.WriteString("    auth?: string | AuthDataGenerator\n")
	buf.WriteString("    transport?: PulseTransport\n")
	buf.WriteString("    disableCapabilityPreflight?: boolean\n")
	buf.WriteString("}\n\n")

	namespaceNames := make([]string, 0, len(g.namespaces))
	for name := range g.namespaces {
		namespaceNames = append(namespaceNames, name)
	}
	sort.Strings(namespaceNames)
	for _, name := range namespaceNames {
		if !tsIdentifier.MatchString(name) {
			continue
		}
		ns := g.namespaces[name]
		if len(ns.methods) == 0 && len(ns.typeOrder) == 0 {
			continue
		}
		buf.WriteString(fmt.Sprintf("export namespace %s {\n", ns.Name))
		for _, typeName := range ns.typeOrder {
			def := ns.types[typeName]
			if def == "" {
				continue
			}
			buf.WriteString(indentBlock(def, 1))
			buf.WriteString("\n\n")
		}
		if len(ns.methods) > 0 {
			buf.WriteString("    export class ServiceClient {\n")
			buf.WriteString("        private baseClient: BaseClient\n\n")
			buf.WriteString("        constructor(baseClient: BaseClient) {\n")
			buf.WriteString("            this.baseClient = baseClient\n")
			for _, method := range ns.methods {
				name := methodNameFromRendered(method)
				if name != "" {
					buf.WriteString(fmt.Sprintf("            this.%s = this.%s.bind(this)\n", name, name))
				}
			}
			buf.WriteString("        }\n\n")
			for i, method := range ns.methods {
				buf.WriteString(indentBlock(method, 2))
				if i != len(ns.methods)-1 {
					buf.WriteString("\n\n")
				}
			}
			buf.WriteString("\n    }\n")
		}
		buf.WriteString("}\n\n")
	}

	buf.WriteString("export type JSONValue = string | number | boolean | null | JSONValue[] | {[key: string]: JSONValue}\n\n")
	buf.WriteString("function encodeQuery(parts: Record<string, string | string[]>): string {\n")
	buf.WriteString("    const pairs: string[] = []\n")
	buf.WriteString("    for (const key in parts) {\n")
	buf.WriteString("        const val = (Array.isArray(parts[key]) ? parts[key] : [parts[key]]) as string[]\n")
	buf.WriteString("        for (const v of val) {\n")
	buf.WriteString("            pairs.push(`${key}=${encodeURIComponent(v)}`)\n")
	buf.WriteString("        }\n")
	buf.WriteString("    }\n")
	buf.WriteString("    return pairs.join(\"&\")\n")
	buf.WriteString("}\n\n")
	buf.WriteString("// @ts-ignore - TS ignore because makeRecord is not always used\n")
	buf.WriteString("function makeRecord<K extends string | number | symbol, V>(record: Record<K, V | undefined>): Record<K, V> {\n")
	buf.WriteString("    for (const key in record) {\n")
	buf.WriteString("        if (record[key] === undefined) {\n")
	buf.WriteString("            delete record[key]\n")
	buf.WriteString("        }\n")
	buf.WriteString("    }\n")
	buf.WriteString("    return record as Record<K, V>\n")
	buf.WriteString("}\n\n")
	buf.WriteString("function encodePathWildcard(value: string): string {\n")
	buf.WriteString("    return value.split(\"/\").map((part) => encodeURIComponent(part)).join(\"/\")\n")
	buf.WriteString("}\n\n")
	buf.WriteString("function encodeQueryValue(value: unknown): string | string[] | undefined {\n")
	buf.WriteString("    if (value === undefined || value === null) {\n")
	buf.WriteString("        return undefined\n")
	buf.WriteString("    }\n")
	buf.WriteString("    if (Array.isArray(value)) {\n")
	buf.WriteString("        return value.map((item) => String(item))\n")
	buf.WriteString("    }\n")
	buf.WriteString("    if (typeof value === \"object\") {\n")
	buf.WriteString("        return JSON.stringify(value)\n")
	buf.WriteString("    }\n")
	buf.WriteString("    return String(value)\n")
	buf.WriteString("}\n\n")
	buf.WriteString("function encodeHeaderValue(value: unknown): string | undefined {\n")
	buf.WriteString("    if (value === undefined || value === null) {\n")
	buf.WriteString("        return undefined\n")
	buf.WriteString("    }\n")
	buf.WriteString("    if (Array.isArray(value)) {\n")
	buf.WriteString("        return value.map((item) => String(item)).join(\",\")\n")
	buf.WriteString("    }\n")
	buf.WriteString("    if (typeof value === \"object\") {\n")
	buf.WriteString("        return JSON.stringify(value)\n")
	buf.WriteString("    }\n")
	buf.WriteString("    return String(value)\n")
	buf.WriteString("}\n\n")
	buf.WriteString("function encodeCookieHeader(values: Record<string, string>): string | undefined {\n")
	buf.WriteString("    const pairs: string[] = []\n")
	buf.WriteString("    for (const key in values) {\n")
	buf.WriteString("        pairs.push(`${encodeURIComponent(key)}=${encodeURIComponent(values[key])}`)\n")
	buf.WriteString("    }\n")
	buf.WriteString("    if (pairs.length === 0) {\n")
	buf.WriteString("        return undefined\n")
	buf.WriteString("    }\n")
	buf.WriteString("    return pairs.join(\"; \")\n")
	buf.WriteString("}\n\n")
	buf.WriteString("// Keep helper symbols referenced for strict TS noUnusedLocals.\n")
	buf.WriteString("void makeRecord\n")
	buf.WriteString("void encodePathWildcard\n")
	buf.WriteString("void encodeQueryValue\n")
	buf.WriteString("void encodeHeaderValue\n")
	buf.WriteString("void encodeCookieHeader\n\n")
	buf.WriteString(`type CallParameters = Omit<RequestInit, "method" | "body" | "headers"> & {` + "\n")
	buf.WriteString("    headers?: Record<string, string>\n")
	buf.WriteString("    query?: Record<string, string | string[]>\n")
	buf.WriteString("}\n\n")
	buf.WriteString("export type PulseTransport = \"auto\" | \"json\" | \"binary\" | \"binary-strict\"\n\n")
	buf.WriteString("export type AuthDataGenerator = () =>\n")
	buf.WriteString("  | string\n")
	buf.WriteString("  | Promise<string | undefined>\n")
	buf.WriteString("  | undefined\n\n")
	buf.WriteString("export type Fetcher = typeof fetch\n\n")
	buf.WriteString("const boundFetch = fetch.bind(globalThis)\n\n")
	buf.WriteString("class BaseClient {\n")
	buf.WriteString("    readonly baseURL: string\n")
	buf.WriteString("    readonly fetcher: Fetcher\n")
	buf.WriteString("    readonly headers: Record<string, string>\n")
	buf.WriteString(`    readonly requestInit: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }` + "\n")
	buf.WriteString("    readonly authGenerator?: AuthDataGenerator\n\n")
	buf.WriteString("    readonly transport: PulseTransport\n")
	buf.WriteString("    readonly disableCapabilityPreflight: boolean\n")
	buf.WriteString("    private capabilitiesPromise?: Promise<WireCapabilities | null>\n\n")
	buf.WriteString("    constructor(baseURL: string, options: ClientOptions) {\n")
	buf.WriteString("        this.baseURL = baseURL\n")
	buf.WriteString("        this.headers = {}\n")
	buf.WriteString("        if (!BROWSER) {\n")
	buf.WriteString(fmt.Sprintf("            this.headers[\"User-Agent\"] = %q\n", slug+"-Generated-TS-Client (Pulse)"))
	buf.WriteString("        }\n")
	buf.WriteString("        this.requestInit = options.requestInit ?? {}\n")
	buf.WriteString("        this.fetcher = options.fetcher ?? boundFetch\n")
	buf.WriteString("        this.transport = options.transport ?? \"auto\"\n")
	buf.WriteString("        this.disableCapabilityPreflight = options.disableCapabilityPreflight ?? false\n")
	buf.WriteString("        if (options.auth !== undefined) {\n")
	buf.WriteString("            const auth = options.auth\n")
	buf.WriteString("            if (typeof auth === \"function\") {\n")
	buf.WriteString("                this.authGenerator = auth\n")
	buf.WriteString("            } else {\n")
	buf.WriteString("                this.authGenerator = () => auth\n")
	buf.WriteString("            }\n")
	buf.WriteString("        }\n")
	buf.WriteString("    }\n\n")
	buf.WriteString("    async getAuthData(): Promise<CallParameters | undefined> {\n")
	buf.WriteString("        let authData: string | undefined\n")
	buf.WriteString("        if (this.authGenerator) {\n")
	buf.WriteString("            const maybePromise = this.authGenerator()\n")
	buf.WriteString("            if (maybePromise instanceof Promise) {\n")
	buf.WriteString("                authData = await maybePromise\n")
	buf.WriteString("            } else {\n")
	buf.WriteString("                authData = maybePromise\n")
	buf.WriteString("            }\n")
	buf.WriteString("        }\n")
	buf.WriteString("        if (!authData) {\n")
	buf.WriteString("            return undefined\n")
	buf.WriteString("        }\n")
	buf.WriteString("        return { headers: { Authorization: \"Bearer \" + authData } }\n")
	buf.WriteString("    }\n\n")
	buf.WriteString("    public async callTypedEndpoint(spec: TypedEndpointCall): Promise<Response> {\n")
	buf.WriteString("        if (this.transport === \"json\" || !spec.binaryAvailable) {\n")
	buf.WriteString("            if (this.transport === \"binary-strict\" && !spec.binaryAvailable) {\n")
	buf.WriteString("                throw new PulseWireFallbackError(`wire transport unavailable for ${spec.endpointID}`)\n")
	buf.WriteString("            }\n")
	buf.WriteString("            return this.callTypedAPI(spec.method, spec.path, spec.jsonBody, spec.params)\n")
	buf.WriteString("        }\n")
	buf.WriteString("        if ((this.transport === \"auto\" || this.transport === \"binary\") && !this.disableCapabilityPreflight) {\n")
	buf.WriteString("            const capabilities = await this.getWireCapabilities()\n")
	buf.WriteString("            const endpoint = capabilities?.endpoints?.[spec.endpointID]\n")
	buf.WriteString("            if (!capabilities || capabilities.wire_schema_hash !== PULSE_WIRE_SCHEMA_HASH || !endpoint?.available || endpoint.schema_hash !== spec.schemaHash) {\n")
	buf.WriteString("                return this.callTypedAPI(spec.method, spec.path, spec.jsonBody, spec.params)\n")
	buf.WriteString("            }\n")
	buf.WriteString("        }\n")
	buf.WriteString("        try {\n")
	buf.WriteString("            return await this.callWireAPI(spec)\n")
	buf.WriteString("        } catch (err) {\n")
	buf.WriteString("            if (err instanceof APIError) {\n")
	buf.WriteString("                throw err\n")
	buf.WriteString("            }\n")
	buf.WriteString("            if (this.transport !== \"binary-strict\" && !(err instanceof PulseWireFallbackError)) {\n")
	buf.WriteString("                return this.callTypedAPI(spec.method, spec.path, spec.jsonBody, spec.params)\n")
	buf.WriteString("            }\n")
	buf.WriteString("            if (this.transport !== \"binary-strict\" && err instanceof PulseWireFallbackError && spec.safeJSONRetry) {\n")
	buf.WriteString("                return this.callTypedAPI(spec.method, spec.path, spec.jsonBody, spec.params)\n")
	buf.WriteString("            }\n")
	buf.WriteString("            throw err\n")
	buf.WriteString("        }\n")
	buf.WriteString("    }\n\n")
	buf.WriteString("    private async callWireAPI(spec: TypedEndpointCall): Promise<Response> {\n")
	buf.WriteString("        const callID = makePulseCallID()\n")
	buf.WriteString("        const payload = encodePulseWire({\n")
	buf.WriteString("            schema_hash: spec.schemaHash,\n")
	buf.WriteString("            method: spec.method,\n")
	buf.WriteString("            path_params: spec.pathParams ?? {},\n")
	buf.WriteString("            payload: spec.payload ?? null,\n")
	buf.WriteString("        })\n")
	buf.WriteString("        const wireParams: CallParameters = {\n")
	buf.WriteString("            ...spec.params,\n")
	buf.WriteString("            headers: {\n")
	buf.WriteString("                ...spec.params?.headers,\n")
	buf.WriteString("                \"Content-Type\": PULSE_WIRE_CONTENT_TYPE,\n")
	buf.WriteString("                \"Accept\": PULSE_WIRE_CONTENT_TYPE,\n")
	buf.WriteString("                \"X-Pulse-Call-ID\": callID,\n")
	buf.WriteString("            },\n")
	buf.WriteString("        }\n")
	buf.WriteString("        let response: Response\n")
	buf.WriteString("        try {\n")
	buf.WriteString("            response = await this.fetchAPI(\"POST\", `/_wire/${encodeURIComponent(spec.endpointID)}`, payload, wireParams)\n")
	buf.WriteString("        } catch (err) {\n")
	buf.WriteString("            if (err instanceof APIError) {\n")
	buf.WriteString("                throw err\n")
	buf.WriteString("            }\n")
	buf.WriteString("            throw err\n")
	buf.WriteString("        }\n")
	buf.WriteString("        const contentType = response.headers.get(\"Content-Type\") ?? \"\"\n")
	buf.WriteString("        if (!contentType.includes(PULSE_WIRE_CONTENT_TYPE)) {\n")
	buf.WriteString("            throw new Error(`unexpected wire response content type: ${contentType}`)\n")
	buf.WriteString("        }\n")
	buf.WriteString("        try {\n")
	buf.WriteString("            return responseFromWireEnvelope(await decodePulseWireResponse(response))\n")
	buf.WriteString("        } catch (err) {\n")
	buf.WriteString("            if (err instanceof APIError) {\n")
	buf.WriteString("                throw err\n")
	buf.WriteString("            }\n")
	buf.WriteString("            const recovered = await this.recoverWireCall(callID)\n")
	buf.WriteString("            if (recovered) {\n")
	buf.WriteString("                return responseFromRecoveredWire(recovered)\n")
	buf.WriteString("            }\n")
	buf.WriteString("            if (spec.safeJSONRetry) {\n")
	buf.WriteString("                throw err\n")
	buf.WriteString("            }\n")
	buf.WriteString("            throw new PulseWireFallbackError(`wire response decode failed for ${spec.endpointID}: ${String(err)}`)\n")
	buf.WriteString("        }\n")
	buf.WriteString("    }\n\n")
	buf.WriteString("    private async getWireCapabilities(): Promise<WireCapabilities | null> {\n")
	buf.WriteString("        if (!this.capabilitiesPromise) {\n")
	buf.WriteString("            this.capabilitiesPromise = (async () => {\n")
	buf.WriteString("                try {\n")
	buf.WriteString("                    const response = await this.callAPI(\"GET\", \"/_wire/capabilities\")\n")
	buf.WriteString("                    return await response.json() as WireCapabilities\n")
	buf.WriteString("                } catch {\n")
	buf.WriteString("                    return null\n")
	buf.WriteString("                }\n")
	buf.WriteString("            })()\n")
	buf.WriteString("        }\n")
	buf.WriteString("        return this.capabilitiesPromise\n")
	buf.WriteString("    }\n\n")
	buf.WriteString("    private async recoverWireCall(callID: string): Promise<RecoveredWireResponse | null> {\n")
	buf.WriteString("        try {\n")
	buf.WriteString("            const response = await this.callAPI(\"GET\", `/_wire/recover/${encodeURIComponent(callID)}`)\n")
	buf.WriteString("            return await response.json() as RecoveredWireResponse\n")
	buf.WriteString("        } catch {\n")
	buf.WriteString("            return null\n")
	buf.WriteString("        }\n")
	buf.WriteString("    }\n\n")
	buf.WriteString("    public async callTypedAPI(method: string, path: string, body?: RequestInit[\"body\"], params?: CallParameters): Promise<Response> {\n")
	buf.WriteString("        return this.callAPI(method, path, body, {\n")
	buf.WriteString("            ...params,\n")
	buf.WriteString("            headers: { \"Content-Type\": \"application/json\", ...params?.headers },\n")
	buf.WriteString("        })\n")
	buf.WriteString("    }\n\n")
	buf.WriteString("    public async callAPI(method: string, path: string, body?: RequestInit[\"body\"], params?: CallParameters): Promise<Response> {\n")
	buf.WriteString("        const response = await this.fetchAPI(method, path, body, params)\n")
	buf.WriteString("        if (!response.ok) {\n")
	buf.WriteString("            let body: APIErrorResponse = { code: ErrCode.Unknown, message: `request failed: status ${response.status}` }\n")
	buf.WriteString("            try {\n")
	buf.WriteString("                const text = await response.text()\n")
	buf.WriteString("                try {\n")
	buf.WriteString("                    const jsonBody = JSON.parse(text)\n")
	buf.WriteString("                    if (isAPIErrorResponse(jsonBody)) {\n")
	buf.WriteString("                        body = jsonBody\n")
	buf.WriteString("                    } else {\n")
	buf.WriteString("                        body.message += \": \" + JSON.stringify(jsonBody)\n")
	buf.WriteString("                    }\n")
	buf.WriteString("                } catch {\n")
	buf.WriteString("                    body.message += \": \" + text\n")
	buf.WriteString("                }\n")
	buf.WriteString("            } catch (err) {\n")
	buf.WriteString("                body.message += \": \" + String(err)\n")
	buf.WriteString("            }\n")
	buf.WriteString("            throw new APIError(response.status, body)\n")
	buf.WriteString("        }\n")
	buf.WriteString("        return response\n")
	buf.WriteString("    }\n\n")
	buf.WriteString("    private async fetchAPI(method: string, path: string, body?: RequestInit[\"body\"], params?: CallParameters): Promise<Response> {\n")
	buf.WriteString("        let { query, headers, ...rest } = params ?? {}\n")
	buf.WriteString("        const init = {\n")
	buf.WriteString("            ...this.requestInit,\n")
	buf.WriteString("            ...rest,\n")
	buf.WriteString("            method,\n")
	buf.WriteString("            body: body ?? null,\n")
	buf.WriteString("        }\n")
	buf.WriteString("        init.headers = { ...this.headers, ...init.headers, ...headers }\n")
	buf.WriteString("        const authData = await this.getAuthData()\n")
	buf.WriteString("        if (authData) {\n")
	buf.WriteString("            if (authData.query) {\n")
	buf.WriteString("                query = { ...query, ...authData.query }\n")
	buf.WriteString("            }\n")
	buf.WriteString("            if (authData.headers) {\n")
	buf.WriteString("                init.headers = { ...init.headers, ...authData.headers }\n")
	buf.WriteString("            }\n")
	buf.WriteString("        }\n")
	buf.WriteString("        const queryString = query ? \"?\" + encodeQuery(query) : \"\"\n")
	buf.WriteString("        return await this.fetcher(this.baseURL + path + queryString, init)\n")
	buf.WriteString("    }\n")
	buf.WriteString("}\n\n")
	buf.WriteString(`interface TypedEndpointCall {
    endpointID: string
    schemaHash: string
    binaryAvailable: boolean
    safeJSONRetry: boolean
    method: string
    path: string
    pathParams?: Record<string, unknown>
    payload?: unknown
    jsonBody?: RequestInit["body"]
    params?: CallParameters
}

interface WireCapabilities {
    wire_schema_hash: string
    endpoints: Record<string, {
        available: boolean
        schema_hash?: string
    }>
}

interface RecoveredWireResponse {
    status: number
    result?: unknown
    error?: APIErrorResponse
}

export class PulseWireFallbackError extends Error {
    constructor(message: string) {
        super(message)
        Object.defineProperty(this, "name", {
            value: "PulseWireFallbackError",
            enumerable: false,
            configurable: true,
        })
        if ((Object as any).setPrototypeOf === undefined) {
            ;(this as any).__proto__ = PulseWireFallbackError.prototype
        } else {
            Object.setPrototypeOf(this, PulseWireFallbackError.prototype)
        }
    }
}

function makePulseCallID(): string {
    const random = new Uint8Array(16)
    const cryptoObj = (globalThis as any).crypto
    if (cryptoObj?.getRandomValues) {
        cryptoObj.getRandomValues(random)
    } else {
        for (let i = 0; i < random.length; i++) {
            random[i] = Math.floor(Math.random() * 256)
        }
    }
    return Array.from(random).map((b) => b.toString(16).padStart(2, "0")).join("")
}

function responseFromRecoveredWire(recovered: RecoveredWireResponse): Response {
    if (recovered.error) {
        throw new APIError(recovered.status || 500, recovered.error)
    }
    return jsonResponse(recovered.result ?? null, recovered.status || 200)
}

function responseFromWireEnvelope(envelope: any): Response {
    if (!envelope || typeof envelope !== "object") {
        throw new Error("invalid wire response envelope")
    }
    const status = typeof envelope.status === "number" ? envelope.status : 200
    if (envelope.ok === false) {
        throw new APIError(status, normalizeAPIErrorResponse(envelope.error, status))
    }
    return jsonResponse(envelope.result ?? null, status)
}

function normalizeAPIErrorResponse(value: any, status: number): APIErrorResponse {
    if (isAPIErrorResponse(value)) {
        return value
    }
    return { code: ErrCode.Unknown, message: ` + "`request failed: status ${status}`" + ` }
}

function jsonResponse(value: unknown, status: number): Response {
    return new Response(JSON.stringify(value), {
        status,
        headers: { "Content-Type": "application/json" },
    })
}

const pulseWireTextEncoder = new TextEncoder()
const pulseWireTextDecoder = new TextDecoder()
const pulseWireMagic = new Uint8Array([80, 87, 66, 49])

function encodePulseWire(value: unknown): Uint8Array {
    const writer = new PulseWireWriter()
    writer.bytes(pulseWireMagic)
    writePulseWireValue(writer, value)
    return writer.finish()
}

async function decodePulseWireResponse(response: Response): Promise<unknown> {
    return decodePulseWire(new Uint8Array(await response.arrayBuffer()))
}

function decodePulseWire(data: Uint8Array): unknown {
    for (let i = 0; i < pulseWireMagic.length; i++) {
        if (data[i] !== pulseWireMagic[i]) {
            throw new Error("invalid wire payload")
        }
    }
    const reader = new PulseWireReader(data.subarray(pulseWireMagic.length))
    const value = reader.value()
    if (!reader.done()) {
        throw new Error("trailing wire payload")
    }
    return value
}

function writePulseWireValue(writer: PulseWireWriter, value: unknown): void {
    if (value === undefined || value === null) {
        writer.byte(0)
        return
    }
    if (typeof value === "boolean") {
        writer.byte(value ? 2 : 1)
        return
    }
    if (typeof value === "number") {
        if (!Number.isFinite(value)) {
            throw new Error("non-finite numbers cannot be encoded")
        }
        writer.byte(3)
        writer.float64(value)
        return
    }
    if (typeof value === "string") {
        writer.byte(4)
        writer.string(value)
        return
    }
    if (Array.isArray(value)) {
        writer.byte(5)
        writer.uvarint(value.length)
        for (const item of value) {
            writePulseWireValue(writer, item)
        }
        return
    }
    if (value instanceof Date) {
        writer.byte(4)
        writer.string(value.toISOString())
        return
    }
    if (typeof value === "object") {
        const record = value as Record<string, unknown>
        const keys = Object.keys(record).filter((key) => record[key] !== undefined).sort()
        writer.byte(6)
        writer.uvarint(keys.length)
        for (const key of keys) {
            writer.string(key)
            writePulseWireValue(writer, record[key])
        }
        return
    }
    throw new Error(` + "`unsupported wire value: ${typeof value}`" + `)
}

class PulseWireWriter {
    private chunks: number[] = []

    byte(value: number): void {
        this.chunks.push(value & 0xff)
    }

    bytes(value: Uint8Array): void {
        for (const b of value) {
            this.byte(b)
        }
    }

    string(value: string): void {
        this.sizedBytes(pulseWireTextEncoder.encode(value))
    }

    sizedBytes(value: Uint8Array): void {
        this.uvarint(value.length)
        this.bytes(value)
    }

    uvarint(value: number): void {
        let v = Math.trunc(value)
        while (v >= 0x80) {
            this.byte((v & 0x7f) | 0x80)
            v = Math.floor(v / 128)
        }
        this.byte(v)
    }

    float64(value: number): void {
        const data = new Uint8Array(8)
        new DataView(data.buffer).setFloat64(0, value, true)
        this.bytes(data)
    }

    finish(): Uint8Array {
        return new Uint8Array(this.chunks)
    }
}

class PulseWireReader {
    private offset = 0

    constructor(private readonly data: Uint8Array) {}

    done(): boolean {
        return this.offset === this.data.length
    }

    value(): unknown {
        const tag = this.byte()
        switch (tag) {
            case 0:
                return null
            case 1:
                return false
            case 2:
                return true
            case 3:
                return this.float64()
            case 4:
                return this.string()
            case 5: {
                const count = this.uvarint()
                const items: unknown[] = []
                for (let i = 0; i < count; i++) {
                    items.push(this.value())
                }
                return items
            }
            case 6: {
                const count = this.uvarint()
                const obj: Record<string, unknown> = {}
                for (let i = 0; i < count; i++) {
                    const key = this.string()
                    obj[key] = this.value()
                }
                return obj
            }
            default:
                throw new Error(` + "`unknown wire tag ${tag}`" + `)
        }
    }

    byte(): number {
        if (this.offset >= this.data.length) {
            throw new Error("truncated wire payload")
        }
        return this.data[this.offset++]
    }

    uvarint(): number {
        let value = 0
        let shift = 0
        for (;;) {
            const b = this.byte()
            value += (b & 0x7f) * Math.pow(2, shift)
            if ((b & 0x80) === 0) {
                return value
            }
            shift += 7
            if (shift > 63) {
                throw new Error("invalid wire length")
            }
        }
    }

    sizedBytes(): Uint8Array {
        const length = this.uvarint()
        if (this.offset + length > this.data.length) {
            throw new Error("truncated wire bytes")
        }
        const out = this.data.subarray(this.offset, this.offset + length)
        this.offset += length
        return out
    }

    string(): string {
        return pulseWireTextDecoder.decode(this.sizedBytes())
    }

    float64(): number {
        if (this.offset + 8 > this.data.length) {
            throw new Error("truncated wire number")
        }
        const value = new DataView(this.data.buffer, this.data.byteOffset + this.offset, 8).getFloat64(0, true)
        this.offset += 8
        return value
    }
}

`)
	buf.WriteString("interface APIErrorResponse {\n")
	buf.WriteString("    code: ErrCode\n")
	buf.WriteString("    message: string\n")
	buf.WriteString("    details?: any\n")
	buf.WriteString("}\n\n")
	buf.WriteString("function isAPIErrorResponse(err: any): err is APIErrorResponse {\n")
	buf.WriteString("    return (\n")
	buf.WriteString("        err !== undefined && err !== null &&\n")
	buf.WriteString("        isErrCode(err.code) &&\n")
	buf.WriteString("        typeof err.message === \"string\" &&\n")
	buf.WriteString("        (err.details === undefined || err.details === null || typeof err.details === \"object\")\n")
	buf.WriteString("    )\n")
	buf.WriteString("}\n\n")
	buf.WriteString("function isErrCode(code: any): code is ErrCode {\n")
	buf.WriteString("    return code !== undefined && Object.values(ErrCode).includes(code)\n")
	buf.WriteString("}\n\n")
	buf.WriteString("export class APIError extends Error {\n")
	buf.WriteString("    public readonly status: number\n")
	buf.WriteString("    public readonly code: ErrCode\n")
	buf.WriteString("    public readonly details?: any\n\n")
	buf.WriteString("    constructor(status: number, response: APIErrorResponse) {\n")
	buf.WriteString("        super(response.message)\n")
	buf.WriteString("        Object.defineProperty(this, \"name\", {\n")
	buf.WriteString("            value: \"APIError\",\n")
	buf.WriteString("            enumerable: false,\n")
	buf.WriteString("            configurable: true,\n")
	buf.WriteString("        })\n")
	buf.WriteString("        if ((Object as any).setPrototypeOf === undefined) {\n")
	buf.WriteString("            ;(this as any).__proto__ = APIError.prototype\n")
	buf.WriteString("        } else {\n")
	buf.WriteString("            Object.setPrototypeOf(this, APIError.prototype)\n")
	buf.WriteString("        }\n")
	buf.WriteString("        if ((Error as any).captureStackTrace !== undefined) {\n")
	buf.WriteString("            ;(Error as any).captureStackTrace(this, this.constructor)\n")
	buf.WriteString("        }\n")
	buf.WriteString("        this.status = status\n")
	buf.WriteString("        this.code = response.code\n")
	buf.WriteString("        this.details = response.details\n")
	buf.WriteString("    }\n")
	buf.WriteString("}\n\n")
	buf.WriteString("export function isAPIError(err: any): err is APIError {\n")
	buf.WriteString("    return err instanceof APIError\n")
	buf.WriteString("}\n\n")
	buf.WriteString("export enum ErrCode {\n")
	for _, item := range []struct {
		Name  string
		Value string
	}{
		{"OK", "ok"},
		{"Canceled", "canceled"},
		{"Unknown", "unknown"},
		{"InvalidArgument", "invalid_argument"},
		{"DeadlineExceeded", "deadline_exceeded"},
		{"NotFound", "not_found"},
		{"AlreadyExists", "already_exists"},
		{"PermissionDenied", "permission_denied"},
		{"ResourceExhausted", "resource_exhausted"},
		{"FailedPrecondition", "failed_precondition"},
		{"Aborted", "aborted"},
		{"OutOfRange", "out_of_range"},
		{"Unimplemented", "unimplemented"},
		{"Internal", "internal"},
		{"Unavailable", "unavailable"},
		{"DataLoss", "data_loss"},
		{"Unauthenticated", "unauthenticated"},
		{"Conflict", "conflict"},
	} {
		buf.WriteString(fmt.Sprintf("    %s = %q,\n", item.Name, item.Value))
	}
	buf.WriteString("}\n")

	return buf.Bytes(), nil
}
