package clientgen

import (
	"bytes"
	"fmt"
	"go/types"
	"reflect"
	"regexp"
	"sort"
	"strconv"
	"strings"

	"pulse.dev/internal/model"
	"pulse.dev/internal/runtimeapi"
	"pulse.dev/internal/wire"
	"pulse.dev/internal/wiremodel"
)

type TypeScriptOptions struct {
	AppSlug string
}

type tsGenerator struct {
	app         *model.App
	opts        TypeScriptOptions
	namespaces  map[string]*tsNamespace
	namespaceMu []string
	namedTypes  map[string]string
	inProgress  map[string]bool
}

type tsNamespace struct {
	Name      string
	typeOrder []string
	types     map[string]string
	methods   []string
}

type requestFieldLocation string

const (
	requestFieldBody   requestFieldLocation = "body"
	requestFieldQuery  requestFieldLocation = "query"
	requestFieldHeader requestFieldLocation = "header"
	requestFieldCookie requestFieldLocation = "cookie"
)

type requestField struct {
	Name     string
	JSONName string
	Type     types.Type
	Location requestFieldLocation
	Target   string
}

var tsIdentifier = regexp.MustCompile(`^[A-Za-z_$][A-Za-z0-9_$]*$`)

func GenerateTypeScript(app *model.App, opts TypeScriptOptions) ([]byte, error) {
	if app == nil {
		return nil, fmt.Errorf("nil app")
	}
	gen := &tsGenerator{
		app:        app,
		opts:       opts,
		namespaces: make(map[string]*tsNamespace),
		namedTypes: make(map[string]string),
		inProgress: make(map[string]bool),
	}

	for _, svc := range app.Services {
		if !tsIdentifier.MatchString(svc.Name) {
			continue
		}
		ns := gen.namespace(svc.Name)
		for _, ep := range svc.Endpoints {
			if ep.Access == runtimeapi.Private {
				continue
			}
			method, err := gen.renderEndpointMethod(svc.Name, ep)
			if err != nil {
				return nil, err
			}
			ns.methods = append(ns.methods, method)
		}
	}

	return gen.render()
}

func (g *tsGenerator) render() ([]byte, error) {
	slug := strings.TrimSpace(g.opts.AppSlug)
	if slug == "" {
		slug = strings.TrimSpace(g.app.Name)
	}
	if slug == "" {
		slug = "pulse"
	}

	var buf bytes.Buffer
	buf.WriteString("// Code generated by Pulse. DO NOT EDIT.\n\n")
	buf.WriteString("/* eslint-disable */\n")
	buf.WriteString("/* jshint ignore:start */\n")
	buf.WriteString("/* jslint-disable */\n\n")
	buf.WriteString("export type BaseURL = string\n\n")
	buf.WriteString(`export const Local: BaseURL = "http://localhost:4000"` + "\n\n")
	buf.WriteString("export function Environment(name: string): BaseURL {\n")
	buf.WriteString(fmt.Sprintf("    return `https://${name}-%s.encr.app`\n", slug))
	buf.WriteString("}\n\n")
	buf.WriteString("export function PreviewEnv(pr: number | string): BaseURL {\n")
	buf.WriteString("    return Environment(`pr${pr}`)\n")
	buf.WriteString("}\n\n")
	buf.WriteString(`const BROWSER = typeof globalThis === "object" && ("window" in globalThis)` + "\n\n")
	capabilities := wiremodel.AppCapabilities(g.app)
	buf.WriteString(fmt.Sprintf("const PULSE_WIRE_SCHEMA_HASH = %q\n", capabilities.SchemaHash))
	buf.WriteString(fmt.Sprintf("const PULSE_WIRE_CONTENT_TYPE = %q\n\n", wire.ContentType))

	serviceNames := make([]string, 0, len(g.namespaces))
	for _, name := range namespaceNamesWithMethods(g.namespaces) {
		serviceNames = append(serviceNames, name)
	}
	sort.Strings(serviceNames)

	buf.WriteString("export default class Client {\n")
	for _, svcName := range serviceNames {
		buf.WriteString(fmt.Sprintf("    public readonly %s: %s.ServiceClient\n", svcName, svcName))
	}
	buf.WriteString("    private readonly options: ClientOptions\n")
	buf.WriteString("    private readonly target: string\n\n")
	buf.WriteString("    constructor(target: string, token?: string)\n")
	buf.WriteString("    constructor(target: BaseURL, options?: ClientOptions)\n")
	buf.WriteString(`    constructor(target: string | BaseURL = "prod", options?: string | ClientOptions) {` + "\n")
	buf.WriteString(`        if (!target.startsWith("http://") && !target.startsWith("https://")) {` + "\n")
	buf.WriteString("            target = Environment(target)\n")
	buf.WriteString("        }\n\n")
	buf.WriteString(`        if (typeof options === "string") {` + "\n")
	buf.WriteString("            options = { auth: options }\n")
	buf.WriteString("        }\n\n")
	buf.WriteString("        this.target = target\n")
	buf.WriteString("        this.options = options ?? {}\n")
	buf.WriteString("        const base = new BaseClient(this.target, this.options)\n")
	for _, svcName := range serviceNames {
		buf.WriteString(fmt.Sprintf("        this.%s = new %s.ServiceClient(base)\n", svcName, svcName))
	}
	buf.WriteString("    }\n\n")
	buf.WriteString("    public with(options: ClientOptions): Client {\n")
	buf.WriteString("        return new Client(this.target, {\n")
	buf.WriteString("            ...this.options,\n")
	buf.WriteString("            ...options,\n")
	buf.WriteString("        })\n")
	buf.WriteString("    }\n")
	buf.WriteString("}\n\n")

	buf.WriteString("export interface ClientOptions {\n")
	buf.WriteString("    fetcher?: Fetcher\n")
	buf.WriteString(`    requestInit?: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }` + "\n")
	buf.WriteString("    auth?: string | AuthDataGenerator\n")
	buf.WriteString("    transport?: PulseTransport\n")
	buf.WriteString("    disableCapabilityPreflight?: boolean\n")
	buf.WriteString("}\n\n")

	namespaceNames := make([]string, 0, len(g.namespaces))
	for name := range g.namespaces {
		namespaceNames = append(namespaceNames, name)
	}
	sort.Strings(namespaceNames)
	for _, name := range namespaceNames {
		if !tsIdentifier.MatchString(name) {
			continue
		}
		ns := g.namespaces[name]
		if len(ns.methods) == 0 && len(ns.typeOrder) == 0 {
			continue
		}
		buf.WriteString(fmt.Sprintf("export namespace %s {\n", ns.Name))
		for _, typeName := range ns.typeOrder {
			def := ns.types[typeName]
			if def == "" {
				continue
			}
			buf.WriteString(indentBlock(def, 1))
			buf.WriteString("\n\n")
		}
		if len(ns.methods) > 0 {
			buf.WriteString("    export class ServiceClient {\n")
			buf.WriteString("        private baseClient: BaseClient\n\n")
			buf.WriteString("        constructor(baseClient: BaseClient) {\n")
			buf.WriteString("            this.baseClient = baseClient\n")
			for _, method := range ns.methods {
				name := methodNameFromRendered(method)
				if name != "" {
					buf.WriteString(fmt.Sprintf("            this.%s = this.%s.bind(this)\n", name, name))
				}
			}
			buf.WriteString("        }\n\n")
			for i, method := range ns.methods {
				buf.WriteString(indentBlock(method, 2))
				if i != len(ns.methods)-1 {
					buf.WriteString("\n\n")
				}
			}
			buf.WriteString("\n    }\n")
		}
		buf.WriteString("}\n\n")
	}

	buf.WriteString("export type JSONValue = string | number | boolean | null | JSONValue[] | {[key: string]: JSONValue}\n\n")
	buf.WriteString("function encodeQuery(parts: Record<string, string | string[]>): string {\n")
	buf.WriteString("    const pairs: string[] = []\n")
	buf.WriteString("    for (const key in parts) {\n")
	buf.WriteString("        const val = (Array.isArray(parts[key]) ? parts[key] : [parts[key]]) as string[]\n")
	buf.WriteString("        for (const v of val) {\n")
	buf.WriteString("            pairs.push(`${key}=${encodeURIComponent(v)}`)\n")
	buf.WriteString("        }\n")
	buf.WriteString("    }\n")
	buf.WriteString("    return pairs.join(\"&\")\n")
	buf.WriteString("}\n\n")
	buf.WriteString("// @ts-ignore - TS ignore because makeRecord is not always used\n")
	buf.WriteString("function makeRecord<K extends string | number | symbol, V>(record: Record<K, V | undefined>): Record<K, V> {\n")
	buf.WriteString("    for (const key in record) {\n")
	buf.WriteString("        if (record[key] === undefined) {\n")
	buf.WriteString("            delete record[key]\n")
	buf.WriteString("        }\n")
	buf.WriteString("    }\n")
	buf.WriteString("    return record as Record<K, V>\n")
	buf.WriteString("}\n\n")
	buf.WriteString("function encodePathWildcard(value: string): string {\n")
	buf.WriteString("    return value.split(\"/\").map((part) => encodeURIComponent(part)).join(\"/\")\n")
	buf.WriteString("}\n\n")
	buf.WriteString("function encodeQueryValue(value: unknown): string | string[] | undefined {\n")
	buf.WriteString("    if (value === undefined || value === null) {\n")
	buf.WriteString("        return undefined\n")
	buf.WriteString("    }\n")
	buf.WriteString("    if (Array.isArray(value)) {\n")
	buf.WriteString("        return value.map((item) => String(item))\n")
	buf.WriteString("    }\n")
	buf.WriteString("    if (typeof value === \"object\") {\n")
	buf.WriteString("        return JSON.stringify(value)\n")
	buf.WriteString("    }\n")
	buf.WriteString("    return String(value)\n")
	buf.WriteString("}\n\n")
	buf.WriteString("function encodeHeaderValue(value: unknown): string | undefined {\n")
	buf.WriteString("    if (value === undefined || value === null) {\n")
	buf.WriteString("        return undefined\n")
	buf.WriteString("    }\n")
	buf.WriteString("    if (Array.isArray(value)) {\n")
	buf.WriteString("        return value.map((item) => String(item)).join(\",\")\n")
	buf.WriteString("    }\n")
	buf.WriteString("    if (typeof value === \"object\") {\n")
	buf.WriteString("        return JSON.stringify(value)\n")
	buf.WriteString("    }\n")
	buf.WriteString("    return String(value)\n")
	buf.WriteString("}\n\n")
	buf.WriteString("function encodeCookieHeader(values: Record<string, string>): string | undefined {\n")
	buf.WriteString("    const pairs: string[] = []\n")
	buf.WriteString("    for (const key in values) {\n")
	buf.WriteString("        pairs.push(`${encodeURIComponent(key)}=${encodeURIComponent(values[key])}`)\n")
	buf.WriteString("    }\n")
	buf.WriteString("    if (pairs.length === 0) {\n")
	buf.WriteString("        return undefined\n")
	buf.WriteString("    }\n")
	buf.WriteString("    return pairs.join(\"; \")\n")
	buf.WriteString("}\n\n")
	buf.WriteString("// Keep helper symbols referenced for strict TS noUnusedLocals.\n")
	buf.WriteString("void makeRecord\n")
	buf.WriteString("void encodePathWildcard\n")
	buf.WriteString("void encodeQueryValue\n")
	buf.WriteString("void encodeHeaderValue\n")
	buf.WriteString("void encodeCookieHeader\n\n")
	buf.WriteString(`type CallParameters = Omit<RequestInit, "method" | "body" | "headers"> & {` + "\n")
	buf.WriteString("    headers?: Record<string, string>\n")
	buf.WriteString("    query?: Record<string, string | string[]>\n")
	buf.WriteString("}\n\n")
	buf.WriteString("export type PulseTransport = \"auto\" | \"json\" | \"binary\" | \"binary-strict\"\n\n")
	buf.WriteString("export type AuthDataGenerator = () =>\n")
	buf.WriteString("  | string\n")
	buf.WriteString("  | Promise<string | undefined>\n")
	buf.WriteString("  | undefined\n\n")
	buf.WriteString("export type Fetcher = typeof fetch\n\n")
	buf.WriteString("const boundFetch = fetch.bind(globalThis)\n\n")
	buf.WriteString("class BaseClient {\n")
	buf.WriteString("    readonly baseURL: string\n")
	buf.WriteString("    readonly fetcher: Fetcher\n")
	buf.WriteString("    readonly headers: Record<string, string>\n")
	buf.WriteString(`    readonly requestInit: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }` + "\n")
	buf.WriteString("    readonly authGenerator?: AuthDataGenerator\n\n")
	buf.WriteString("    readonly transport: PulseTransport\n")
	buf.WriteString("    readonly disableCapabilityPreflight: boolean\n")
	buf.WriteString("    private capabilitiesPromise?: Promise<WireCapabilities | null>\n\n")
	buf.WriteString("    constructor(baseURL: string, options: ClientOptions) {\n")
	buf.WriteString("        this.baseURL = baseURL\n")
	buf.WriteString("        this.headers = {}\n")
	buf.WriteString("        if (!BROWSER) {\n")
	buf.WriteString(fmt.Sprintf("            this.headers[\"User-Agent\"] = %q\n", slug+"-Generated-TS-Client (Pulse)"))
	buf.WriteString("        }\n")
	buf.WriteString("        this.requestInit = options.requestInit ?? {}\n")
	buf.WriteString("        this.fetcher = options.fetcher ?? boundFetch\n")
	buf.WriteString("        this.transport = options.transport ?? \"auto\"\n")
	buf.WriteString("        this.disableCapabilityPreflight = options.disableCapabilityPreflight ?? false\n")
	buf.WriteString("        if (options.auth !== undefined) {\n")
	buf.WriteString("            const auth = options.auth\n")
	buf.WriteString("            if (typeof auth === \"function\") {\n")
	buf.WriteString("                this.authGenerator = auth\n")
	buf.WriteString("            } else {\n")
	buf.WriteString("                this.authGenerator = () => auth\n")
	buf.WriteString("            }\n")
	buf.WriteString("        }\n")
	buf.WriteString("    }\n\n")
	buf.WriteString("    async getAuthData(): Promise<CallParameters | undefined> {\n")
	buf.WriteString("        let authData: string | undefined\n")
	buf.WriteString("        if (this.authGenerator) {\n")
	buf.WriteString("            const maybePromise = this.authGenerator()\n")
	buf.WriteString("            if (maybePromise instanceof Promise) {\n")
	buf.WriteString("                authData = await maybePromise\n")
	buf.WriteString("            } else {\n")
	buf.WriteString("                authData = maybePromise\n")
	buf.WriteString("            }\n")
	buf.WriteString("        }\n")
	buf.WriteString("        if (!authData) {\n")
	buf.WriteString("            return undefined\n")
	buf.WriteString("        }\n")
	buf.WriteString("        return { headers: { Authorization: \"Bearer \" + authData } }\n")
	buf.WriteString("    }\n\n")
	buf.WriteString("    public async callTypedEndpoint(spec: TypedEndpointCall): Promise<Response> {\n")
	buf.WriteString("        if (this.transport === \"json\" || !spec.binaryAvailable) {\n")
	buf.WriteString("            if (this.transport === \"binary-strict\" && !spec.binaryAvailable) {\n")
	buf.WriteString("                throw new PulseWireFallbackError(`wire transport unavailable for ${spec.endpointID}`)\n")
	buf.WriteString("            }\n")
	buf.WriteString("            return this.callTypedAPI(spec.method, spec.path, spec.jsonBody, spec.params)\n")
	buf.WriteString("        }\n")
	buf.WriteString("        if ((this.transport === \"auto\" || this.transport === \"binary\") && !this.disableCapabilityPreflight) {\n")
	buf.WriteString("            const capabilities = await this.getWireCapabilities()\n")
	buf.WriteString("            const endpoint = capabilities?.endpoints?.[spec.endpointID]\n")
	buf.WriteString("            if (!capabilities || capabilities.wire_schema_hash !== PULSE_WIRE_SCHEMA_HASH || !endpoint?.available || endpoint.schema_hash !== spec.schemaHash) {\n")
	buf.WriteString("                return this.callTypedAPI(spec.method, spec.path, spec.jsonBody, spec.params)\n")
	buf.WriteString("            }\n")
	buf.WriteString("        }\n")
	buf.WriteString("        try {\n")
	buf.WriteString("            return await this.callWireAPI(spec)\n")
	buf.WriteString("        } catch (err) {\n")
	buf.WriteString("            if (err instanceof APIError) {\n")
	buf.WriteString("                throw err\n")
	buf.WriteString("            }\n")
	buf.WriteString("            if (this.transport !== \"binary-strict\" && !(err instanceof PulseWireFallbackError)) {\n")
	buf.WriteString("                return this.callTypedAPI(spec.method, spec.path, spec.jsonBody, spec.params)\n")
	buf.WriteString("            }\n")
	buf.WriteString("            if (this.transport !== \"binary-strict\" && err instanceof PulseWireFallbackError && spec.safeJSONRetry) {\n")
	buf.WriteString("                return this.callTypedAPI(spec.method, spec.path, spec.jsonBody, spec.params)\n")
	buf.WriteString("            }\n")
	buf.WriteString("            throw err\n")
	buf.WriteString("        }\n")
	buf.WriteString("    }\n\n")
	buf.WriteString("    private async callWireAPI(spec: TypedEndpointCall): Promise<Response> {\n")
	buf.WriteString("        const callID = makePulseCallID()\n")
	buf.WriteString("        const payload = encodePulseWire({\n")
	buf.WriteString("            schema_hash: spec.schemaHash,\n")
	buf.WriteString("            method: spec.method,\n")
	buf.WriteString("            path_params: spec.pathParams ?? {},\n")
	buf.WriteString("            payload: spec.payload ?? null,\n")
	buf.WriteString("        })\n")
	buf.WriteString("        const wireParams: CallParameters = {\n")
	buf.WriteString("            ...spec.params,\n")
	buf.WriteString("            headers: {\n")
	buf.WriteString("                ...spec.params?.headers,\n")
	buf.WriteString("                \"Content-Type\": PULSE_WIRE_CONTENT_TYPE,\n")
	buf.WriteString("                \"Accept\": PULSE_WIRE_CONTENT_TYPE,\n")
	buf.WriteString("                \"X-Pulse-Call-ID\": callID,\n")
	buf.WriteString("            },\n")
	buf.WriteString("        }\n")
	buf.WriteString("        let response: Response\n")
	buf.WriteString("        try {\n")
	buf.WriteString("            response = await this.fetchAPI(\"POST\", `/_wire/${encodeURIComponent(spec.endpointID)}`, payload, wireParams)\n")
	buf.WriteString("        } catch (err) {\n")
	buf.WriteString("            if (err instanceof APIError) {\n")
	buf.WriteString("                throw err\n")
	buf.WriteString("            }\n")
	buf.WriteString("            throw err\n")
	buf.WriteString("        }\n")
	buf.WriteString("        const contentType = response.headers.get(\"Content-Type\") ?? \"\"\n")
	buf.WriteString("        if (!contentType.includes(PULSE_WIRE_CONTENT_TYPE)) {\n")
	buf.WriteString("            throw new Error(`unexpected wire response content type: ${contentType}`)\n")
	buf.WriteString("        }\n")
	buf.WriteString("        try {\n")
	buf.WriteString("            return responseFromWireEnvelope(await decodePulseWireResponse(response))\n")
	buf.WriteString("        } catch (err) {\n")
	buf.WriteString("            if (err instanceof APIError) {\n")
	buf.WriteString("                throw err\n")
	buf.WriteString("            }\n")
	buf.WriteString("            const recovered = await this.recoverWireCall(callID)\n")
	buf.WriteString("            if (recovered) {\n")
	buf.WriteString("                return responseFromRecoveredWire(recovered)\n")
	buf.WriteString("            }\n")
	buf.WriteString("            if (spec.safeJSONRetry) {\n")
	buf.WriteString("                throw err\n")
	buf.WriteString("            }\n")
	buf.WriteString("            throw new PulseWireFallbackError(`wire response decode failed for ${spec.endpointID}: ${String(err)}`)\n")
	buf.WriteString("        }\n")
	buf.WriteString("    }\n\n")
	buf.WriteString("    private async getWireCapabilities(): Promise<WireCapabilities | null> {\n")
	buf.WriteString("        if (!this.capabilitiesPromise) {\n")
	buf.WriteString("            this.capabilitiesPromise = (async () => {\n")
	buf.WriteString("                try {\n")
	buf.WriteString("                    const response = await this.callAPI(\"GET\", \"/_wire/capabilities\")\n")
	buf.WriteString("                    return await response.json() as WireCapabilities\n")
	buf.WriteString("                } catch {\n")
	buf.WriteString("                    return null\n")
	buf.WriteString("                }\n")
	buf.WriteString("            })()\n")
	buf.WriteString("        }\n")
	buf.WriteString("        return this.capabilitiesPromise\n")
	buf.WriteString("    }\n\n")
	buf.WriteString("    private async recoverWireCall(callID: string): Promise<RecoveredWireResponse | null> {\n")
	buf.WriteString("        try {\n")
	buf.WriteString("            const response = await this.callAPI(\"GET\", `/_wire/recover/${encodeURIComponent(callID)}`)\n")
	buf.WriteString("            return await response.json() as RecoveredWireResponse\n")
	buf.WriteString("        } catch {\n")
	buf.WriteString("            return null\n")
	buf.WriteString("        }\n")
	buf.WriteString("    }\n\n")
	buf.WriteString("    public async callTypedAPI(method: string, path: string, body?: RequestInit[\"body\"], params?: CallParameters): Promise<Response> {\n")
	buf.WriteString("        return this.callAPI(method, path, body, {\n")
	buf.WriteString("            ...params,\n")
	buf.WriteString("            headers: { \"Content-Type\": \"application/json\", ...params?.headers },\n")
	buf.WriteString("        })\n")
	buf.WriteString("    }\n\n")
	buf.WriteString("    public async callAPI(method: string, path: string, body?: RequestInit[\"body\"], params?: CallParameters): Promise<Response> {\n")
	buf.WriteString("        const response = await this.fetchAPI(method, path, body, params)\n")
	buf.WriteString("        if (!response.ok) {\n")
	buf.WriteString("            let body: APIErrorResponse = { code: ErrCode.Unknown, message: `request failed: status ${response.status}` }\n")
	buf.WriteString("            try {\n")
	buf.WriteString("                const text = await response.text()\n")
	buf.WriteString("                try {\n")
	buf.WriteString("                    const jsonBody = JSON.parse(text)\n")
	buf.WriteString("                    if (isAPIErrorResponse(jsonBody)) {\n")
	buf.WriteString("                        body = jsonBody\n")
	buf.WriteString("                    } else {\n")
	buf.WriteString("                        body.message += \": \" + JSON.stringify(jsonBody)\n")
	buf.WriteString("                    }\n")
	buf.WriteString("                } catch {\n")
	buf.WriteString("                    body.message += \": \" + text\n")
	buf.WriteString("                }\n")
	buf.WriteString("            } catch (err) {\n")
	buf.WriteString("                body.message += \": \" + String(err)\n")
	buf.WriteString("            }\n")
	buf.WriteString("            throw new APIError(response.status, body)\n")
	buf.WriteString("        }\n")
	buf.WriteString("        return response\n")
	buf.WriteString("    }\n\n")
	buf.WriteString("    private async fetchAPI(method: string, path: string, body?: RequestInit[\"body\"], params?: CallParameters): Promise<Response> {\n")
	buf.WriteString("        let { query, headers, ...rest } = params ?? {}\n")
	buf.WriteString("        const init = {\n")
	buf.WriteString("            ...this.requestInit,\n")
	buf.WriteString("            ...rest,\n")
	buf.WriteString("            method,\n")
	buf.WriteString("            body: body ?? null,\n")
	buf.WriteString("        }\n")
	buf.WriteString("        init.headers = { ...this.headers, ...init.headers, ...headers }\n")
	buf.WriteString("        const authData = await this.getAuthData()\n")
	buf.WriteString("        if (authData) {\n")
	buf.WriteString("            if (authData.query) {\n")
	buf.WriteString("                query = { ...query, ...authData.query }\n")
	buf.WriteString("            }\n")
	buf.WriteString("            if (authData.headers) {\n")
	buf.WriteString("                init.headers = { ...init.headers, ...authData.headers }\n")
	buf.WriteString("            }\n")
	buf.WriteString("        }\n")
	buf.WriteString("        const queryString = query ? \"?\" + encodeQuery(query) : \"\"\n")
	buf.WriteString("        return await this.fetcher(this.baseURL + path + queryString, init)\n")
	buf.WriteString("    }\n")
	buf.WriteString("}\n\n")
	buf.WriteString(`interface TypedEndpointCall {
    endpointID: string
    schemaHash: string
    binaryAvailable: boolean
    safeJSONRetry: boolean
    method: string
    path: string
    pathParams?: Record<string, unknown>
    payload?: unknown
    jsonBody?: RequestInit["body"]
    params?: CallParameters
}

interface WireCapabilities {
    wire_schema_hash: string
    endpoints: Record<string, {
        available: boolean
        schema_hash?: string
    }>
}

interface RecoveredWireResponse {
    status: number
    result?: unknown
    error?: APIErrorResponse
}

export class PulseWireFallbackError extends Error {
    constructor(message: string) {
        super(message)
        Object.defineProperty(this, "name", {
            value: "PulseWireFallbackError",
            enumerable: false,
            configurable: true,
        })
        if ((Object as any).setPrototypeOf === undefined) {
            ;(this as any).__proto__ = PulseWireFallbackError.prototype
        } else {
            Object.setPrototypeOf(this, PulseWireFallbackError.prototype)
        }
    }
}

function makePulseCallID(): string {
    const random = new Uint8Array(16)
    const cryptoObj = (globalThis as any).crypto
    if (cryptoObj?.getRandomValues) {
        cryptoObj.getRandomValues(random)
    } else {
        for (let i = 0; i < random.length; i++) {
            random[i] = Math.floor(Math.random() * 256)
        }
    }
    return Array.from(random).map((b) => b.toString(16).padStart(2, "0")).join("")
}

function responseFromRecoveredWire(recovered: RecoveredWireResponse): Response {
    if (recovered.error) {
        throw new APIError(recovered.status || 500, recovered.error)
    }
    return jsonResponse(recovered.result ?? null, recovered.status || 200)
}

function responseFromWireEnvelope(envelope: any): Response {
    if (!envelope || typeof envelope !== "object") {
        throw new Error("invalid wire response envelope")
    }
    const status = typeof envelope.status === "number" ? envelope.status : 200
    if (envelope.ok === false) {
        throw new APIError(status, normalizeAPIErrorResponse(envelope.error, status))
    }
    return jsonResponse(envelope.result ?? null, status)
}

function normalizeAPIErrorResponse(value: any, status: number): APIErrorResponse {
    if (isAPIErrorResponse(value)) {
        return value
    }
    return { code: ErrCode.Unknown, message: ` + "`request failed: status ${status}`" + ` }
}

function jsonResponse(value: unknown, status: number): Response {
    return new Response(JSON.stringify(value), {
        status,
        headers: { "Content-Type": "application/json" },
    })
}

const pulseWireTextEncoder = new TextEncoder()
const pulseWireTextDecoder = new TextDecoder()
const pulseWireMagic = new Uint8Array([80, 87, 66, 49])

function encodePulseWire(value: unknown): Uint8Array {
    const writer = new PulseWireWriter()
    writer.bytes(pulseWireMagic)
    writePulseWireValue(writer, value)
    return writer.finish()
}

async function decodePulseWireResponse(response: Response): Promise<unknown> {
    return decodePulseWire(new Uint8Array(await response.arrayBuffer()))
}

function decodePulseWire(data: Uint8Array): unknown {
    for (let i = 0; i < pulseWireMagic.length; i++) {
        if (data[i] !== pulseWireMagic[i]) {
            throw new Error("invalid wire payload")
        }
    }
    const reader = new PulseWireReader(data.subarray(pulseWireMagic.length))
    const value = reader.value()
    if (!reader.done()) {
        throw new Error("trailing wire payload")
    }
    return value
}

function writePulseWireValue(writer: PulseWireWriter, value: unknown): void {
    if (value === undefined || value === null) {
        writer.byte(0)
        return
    }
    if (typeof value === "boolean") {
        writer.byte(value ? 2 : 1)
        return
    }
    if (typeof value === "number") {
        if (!Number.isFinite(value)) {
            throw new Error("non-finite numbers cannot be encoded")
        }
        writer.byte(3)
        writer.float64(value)
        return
    }
    if (typeof value === "string") {
        writer.byte(4)
        writer.string(value)
        return
    }
    if (Array.isArray(value)) {
        writer.byte(5)
        writer.uvarint(value.length)
        for (const item of value) {
            writePulseWireValue(writer, item)
        }
        return
    }
    if (value instanceof Date) {
        writer.byte(4)
        writer.string(value.toISOString())
        return
    }
    if (typeof value === "object") {
        const record = value as Record<string, unknown>
        const keys = Object.keys(record).filter((key) => record[key] !== undefined).sort()
        writer.byte(6)
        writer.uvarint(keys.length)
        for (const key of keys) {
            writer.string(key)
            writePulseWireValue(writer, record[key])
        }
        return
    }
    throw new Error(` + "`unsupported wire value: ${typeof value}`" + `)
}

class PulseWireWriter {
    private chunks: number[] = []

    byte(value: number): void {
        this.chunks.push(value & 0xff)
    }

    bytes(value: Uint8Array): void {
        for (const b of value) {
            this.byte(b)
        }
    }

    string(value: string): void {
        this.sizedBytes(pulseWireTextEncoder.encode(value))
    }

    sizedBytes(value: Uint8Array): void {
        this.uvarint(value.length)
        this.bytes(value)
    }

    uvarint(value: number): void {
        let v = Math.trunc(value)
        while (v >= 0x80) {
            this.byte((v & 0x7f) | 0x80)
            v = Math.floor(v / 128)
        }
        this.byte(v)
    }

    float64(value: number): void {
        const data = new Uint8Array(8)
        new DataView(data.buffer).setFloat64(0, value, true)
        this.bytes(data)
    }

    finish(): Uint8Array {
        return new Uint8Array(this.chunks)
    }
}

class PulseWireReader {
    private offset = 0

    constructor(private readonly data: Uint8Array) {}

    done(): boolean {
        return this.offset === this.data.length
    }

    value(): unknown {
        const tag = this.byte()
        switch (tag) {
            case 0:
                return null
            case 1:
                return false
            case 2:
                return true
            case 3:
                return this.float64()
            case 4:
                return this.string()
            case 5: {
                const count = this.uvarint()
                const items: unknown[] = []
                for (let i = 0; i < count; i++) {
                    items.push(this.value())
                }
                return items
            }
            case 6: {
                const count = this.uvarint()
                const obj: Record<string, unknown> = {}
                for (let i = 0; i < count; i++) {
                    const key = this.string()
                    obj[key] = this.value()
                }
                return obj
            }
            default:
                throw new Error(` + "`unknown wire tag ${tag}`" + `)
        }
    }

    byte(): number {
        if (this.offset >= this.data.length) {
            throw new Error("truncated wire payload")
        }
        return this.data[this.offset++]
    }

    uvarint(): number {
        let value = 0
        let shift = 0
        for (;;) {
            const b = this.byte()
            value += (b & 0x7f) * Math.pow(2, shift)
            if ((b & 0x80) === 0) {
                return value
            }
            shift += 7
            if (shift > 63) {
                throw new Error("invalid wire length")
            }
        }
    }

    sizedBytes(): Uint8Array {
        const length = this.uvarint()
        if (this.offset + length > this.data.length) {
            throw new Error("truncated wire bytes")
        }
        const out = this.data.subarray(this.offset, this.offset + length)
        this.offset += length
        return out
    }

    string(): string {
        return pulseWireTextDecoder.decode(this.sizedBytes())
    }

    float64(): number {
        if (this.offset + 8 > this.data.length) {
            throw new Error("truncated wire number")
        }
        const value = new DataView(this.data.buffer, this.data.byteOffset + this.offset, 8).getFloat64(0, true)
        this.offset += 8
        return value
    }
}

`)
	buf.WriteString("interface APIErrorResponse {\n")
	buf.WriteString("    code: ErrCode\n")
	buf.WriteString("    message: string\n")
	buf.WriteString("    details?: any\n")
	buf.WriteString("}\n\n")
	buf.WriteString("function isAPIErrorResponse(err: any): err is APIErrorResponse {\n")
	buf.WriteString("    return (\n")
	buf.WriteString("        err !== undefined && err !== null &&\n")
	buf.WriteString("        isErrCode(err.code) &&\n")
	buf.WriteString("        typeof err.message === \"string\" &&\n")
	buf.WriteString("        (err.details === undefined || err.details === null || typeof err.details === \"object\")\n")
	buf.WriteString("    )\n")
	buf.WriteString("}\n\n")
	buf.WriteString("function isErrCode(code: any): code is ErrCode {\n")
	buf.WriteString("    return code !== undefined && Object.values(ErrCode).includes(code)\n")
	buf.WriteString("}\n\n")
	buf.WriteString("export class APIError extends Error {\n")
	buf.WriteString("    public readonly status: number\n")
	buf.WriteString("    public readonly code: ErrCode\n")
	buf.WriteString("    public readonly details?: any\n\n")
	buf.WriteString("    constructor(status: number, response: APIErrorResponse) {\n")
	buf.WriteString("        super(response.message)\n")
	buf.WriteString("        Object.defineProperty(this, \"name\", {\n")
	buf.WriteString("            value: \"APIError\",\n")
	buf.WriteString("            enumerable: false,\n")
	buf.WriteString("            configurable: true,\n")
	buf.WriteString("        })\n")
	buf.WriteString("        if ((Object as any).setPrototypeOf === undefined) {\n")
	buf.WriteString("            ;(this as any).__proto__ = APIError.prototype\n")
	buf.WriteString("        } else {\n")
	buf.WriteString("            Object.setPrototypeOf(this, APIError.prototype)\n")
	buf.WriteString("        }\n")
	buf.WriteString("        if ((Error as any).captureStackTrace !== undefined) {\n")
	buf.WriteString("            ;(Error as any).captureStackTrace(this, this.constructor)\n")
	buf.WriteString("        }\n")
	buf.WriteString("        this.status = status\n")
	buf.WriteString("        this.code = response.code\n")
	buf.WriteString("        this.details = response.details\n")
	buf.WriteString("    }\n")
	buf.WriteString("}\n\n")
	buf.WriteString("export function isAPIError(err: any): err is APIError {\n")
	buf.WriteString("    return err instanceof APIError\n")
	buf.WriteString("}\n\n")
	buf.WriteString("export enum ErrCode {\n")
	for _, item := range []struct {
		Name  string
		Value string
	}{
		{"OK", "ok"},
		{"Canceled", "canceled"},
		{"Unknown", "unknown"},
		{"InvalidArgument", "invalid_argument"},
		{"DeadlineExceeded", "deadline_exceeded"},
		{"NotFound", "not_found"},
		{"AlreadyExists", "already_exists"},
		{"PermissionDenied", "permission_denied"},
		{"ResourceExhausted", "resource_exhausted"},
		{"FailedPrecondition", "failed_precondition"},
		{"Aborted", "aborted"},
		{"OutOfRange", "out_of_range"},
		{"Unimplemented", "unimplemented"},
		{"Internal", "internal"},
		{"Unavailable", "unavailable"},
		{"DataLoss", "data_loss"},
		{"Unauthenticated", "unauthenticated"},
		{"Conflict", "conflict"},
	} {
		buf.WriteString(fmt.Sprintf("    %s = %q,\n", item.Name, item.Value))
	}
	buf.WriteString("}\n")

	return buf.Bytes(), nil
}

func (g *tsGenerator) renderEndpointMethod(namespace string, ep *model.Endpoint) (string, error) {
	if ep == nil {
		return "", fmt.Errorf("nil endpoint")
	}

	pathExpr := renderPathExpression(ep.Path)
	if ep.Raw {
		return g.renderRawMethod(pathExpr, ep)
	}

	methodName := preferredHTTPMethod(ep.Methods)
	params := make([]string, 0, len(ep.PathParams)+1)
	for _, pathParam := range ep.PathParams {
		params = append(params, fmt.Sprintf("%s: %s", pathParam.Name, tsTypeForParamKind(pathParam.Kind)))
	}

	payloadType := ""
	if ep.Payload != nil && ep.Payload.Type != nil {
		var err error
		payloadType, err = g.typeRef(ep.Payload.Type, namespace)
		if err != nil {
			return "", err
		}
		params = append(params, fmt.Sprintf("params: %s", payloadType))
	}

	responseType := "void"
	if ep.Response != nil && ep.Response.Type != nil {
		var err error
		responseType, err = g.typeRef(ep.Response.Type, namespace)
		if err != nil {
			return "", err
		}
	}

	var lines []string
	if ep.Payload != nil && ep.Payload.Type != nil {
		fields, ok := extractRequestFields(ep.Payload.Type, queryDefaultMethod(methodName))
		if ok {
			var queryLines []string
			var headerLines []string
			var cookieLines []string
			var bodyLines []string
			for _, field := range fields {
				accessor := "params." + field.Name
				switch field.Location {
				case requestFieldQuery:
					queryLines = append(queryLines, fmt.Sprintf("%s: %s", tsPropertyName(field.Target), "encodeQueryValue("+accessor+")"))
				case requestFieldHeader:
					headerLines = append(headerLines, fmt.Sprintf("%q: encodeHeaderValue(%s)", field.Target, accessor))
				case requestFieldCookie:
					cookieLines = append(cookieLines, fmt.Sprintf("%q: encodeHeaderValue(%s)", field.Target, accessor))
				case requestFieldBody:
					bodyLines = append(bodyLines, fmt.Sprintf("%s: %s", tsPropertyName(field.JSONName), accessor))
				}
			}
			if len(queryLines) > 0 {
				lines = append(lines, "const query = makeRecord<string, string | string[]>({")
				for _, line := range queryLines {
					lines = append(lines, "    "+line+",")
				}
				lines = append(lines, "})")
			}
			if len(headerLines) > 0 || len(cookieLines) > 0 {
				lines = append(lines, "const headers = makeRecord<string, string>({")
				for _, line := range headerLines {
					lines = append(lines, "    "+line+",")
				}
				if len(cookieLines) > 0 {
					lines = append(lines, "    \"Cookie\": encodeCookieHeader(makeRecord<string, string>({")
					for _, line := range cookieLines {
						lines = append(lines, "        "+line+",")
					}
					lines = append(lines, "    })),")
				}
				lines = append(lines, "})")
			}

			bodyExpr := "undefined"
			if !queryDefaultMethod(methodName) {
				switch {
				case len(bodyLines) == 0:
					bodyExpr = "undefined"
				case canPassPayloadAsJSON(fields):
					bodyExpr = "JSON.stringify(params)"
				default:
					lines = append(lines, "const body = {")
					for _, line := range bodyLines {
						lines = append(lines, "    "+line+",")
					}
					lines = append(lines, "}")
					bodyExpr = "JSON.stringify(body)"
				}
			}

			optionsExpr := renderCallOptions(len(queryLines) > 0, len(headerLines) > 0 || len(cookieLines) > 0)
			lines = append(lines, renderTypedEndpointCall(ep, methodName, pathExpr, bodyExpr, optionsExpr, ep.Payload != nil))
		} else {
			lines = append(lines, renderTypedEndpointCall(ep, methodName, pathExpr, "JSON.stringify(params)", "", true))
		}
	} else {
		lines = append(lines, renderTypedEndpointCall(ep, methodName, pathExpr, "undefined", "", false))
	}

	if responseType == "void" {
		lines[len(lines)-1] = strings.Replace(lines[len(lines)-1], "const resp = await ", "await ", 1)
	} else {
		lines = append(lines, fmt.Sprintf("return await resp.json() as %s", responseType))
	}

	var buf bytes.Buffer
	buf.WriteString(fmt.Sprintf("public async %s(%s): Promise<%s> {\n", ep.Name, strings.Join(params, ", "), responseType))
	for _, line := range lines {
		buf.WriteString("    " + line + "\n")
	}
	buf.WriteString("}")
	return buf.String(), nil
}

func (g *tsGenerator) renderRawMethod(pathExpr string, ep *model.Endpoint) (string, error) {
	rawPathParams := rawPathParamNames(ep.Path)
	params := make([]string, 0, len(rawPathParams)+3)
	for _, pathParam := range rawPathParams {
		params = append(params, fmt.Sprintf("%s: string", pathParam))
	}
	methodType := "string"
	if len(ep.Methods) == 1 && ep.Methods[0] != "*" {
		methodType = strconv.Quote(ep.Methods[0])
	}
	params = append(params, fmt.Sprintf("method: %s", methodType))
	params = append(params, `body?: RequestInit["body"]`)
	params = append(params, "options?: CallParameters")

	var buf bytes.Buffer
	buf.WriteString(fmt.Sprintf("public async %s(%s): Promise<globalThis.Response> {\n", ep.Name, strings.Join(params, ", ")))
	buf.WriteString(fmt.Sprintf("    return await this.baseClient.callAPI(method, %s, body, options)\n", pathExpr))
	buf.WriteString("}")
	return buf.String(), nil
}

func (g *tsGenerator) namespace(name string) *tsNamespace {
	if ns, ok := g.namespaces[name]; ok {
		return ns
	}
	ns := &tsNamespace{
		Name:  name,
		types: make(map[string]string),
	}
	g.namespaces[name] = ns
	g.namespaceMu = append(g.namespaceMu, name)
	return ns
}

func (g *tsGenerator) typeRef(typ types.Type, currentNamespace string) (string, error) {
	if typ == nil {
		return "JSONValue", nil
	}

	switch value := typ.(type) {
	case *types.Pointer:
		return g.typeRef(value.Elem(), currentNamespace)
	case *types.Named:
		if special, ok := specialTypeRef(value); ok {
			return special, nil
		}
		return g.ensureNamedType(currentNamespace, value)
	case *types.Alias:
		return g.typeRef(types.Unalias(value), currentNamespace)
	case *types.Basic:
		return tsPrimitive(value), nil
	case *types.Slice:
		if isByteSlice(value) {
			return "string", nil
		}
		elem, err := g.typeRef(value.Elem(), currentNamespace)
		if err != nil {
			return "", err
		}
		return elem + "[]", nil
	case *types.Array:
		elem, err := g.typeRef(value.Elem(), currentNamespace)
		if err != nil {
			return "", err
		}
		return elem + "[]", nil
	case *types.Map:
		elem, err := g.typeRef(value.Elem(), currentNamespace)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("Record<string, %s>", elem), nil
	case *types.Struct:
		return g.inlineStructType(value, currentNamespace)
	case *types.Interface:
		return "JSONValue", nil
	default:
		return "JSONValue", nil
	}
}

func (g *tsGenerator) ensureNamedType(currentNamespace string, named *types.Named) (string, error) {
	id := namedTypeID(named)
	if ref, ok := g.namedTypes[id]; ok {
		return ref, nil
	}
	obj := named.Obj()
	if obj == nil {
		underlying := named.Underlying()
		return g.typeRef(underlying, currentNamespace)
	}
	nsName := namespaceForNamed(obj)
	ref := obj.Name()
	if nsName != currentNamespace {
		ref = nsName + "." + ref
	}
	g.namedTypes[id] = ref
	if g.inProgress[id] {
		return ref, nil
	}

	g.inProgress[id] = true
	def, err := g.renderNamedDefinition(nsName, named)
	delete(g.inProgress, id)
	if err != nil {
		return "", err
	}
	if def != "" {
		ns := g.namespace(nsName)
		if _, exists := ns.types[obj.Name()]; !exists {
			ns.types[obj.Name()] = def
			ns.typeOrder = append(ns.typeOrder, obj.Name())
		}
	}
	return ref, nil
}

func (g *tsGenerator) renderNamedDefinition(namespace string, named *types.Named) (string, error) {
	obj := named.Obj()
	if obj == nil {
		return "", nil
	}
	name := obj.Name()
	switch underlying := named.Underlying().(type) {
	case *types.Basic:
		return fmt.Sprintf("export type %s = %s", name, tsPrimitive(underlying)), nil
	case *types.Slice:
		ref, err := g.typeRef(underlying, namespace)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("export type %s = %s", name, ref), nil
	case *types.Array:
		ref, err := g.typeRef(underlying, namespace)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("export type %s = %s", name, ref), nil
	case *types.Map:
		ref, err := g.typeRef(underlying, namespace)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("export type %s = %s", name, ref), nil
	case *types.Pointer:
		ref, err := g.typeRef(underlying.Elem(), namespace)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("export type %s = %s", name, ref), nil
	case *types.Interface:
		return fmt.Sprintf("export type %s = JSONValue", name), nil
	case *types.Struct:
		var buf bytes.Buffer
		buf.WriteString(fmt.Sprintf("export interface %s {\n", name))
		wroteField := false
		for i := 0; i < underlying.NumFields(); i++ {
			field := underlying.Field(i)
			if !field.Exported() {
				continue
			}
			tag := underlying.Tag(i)
			jsonName := jsonFieldName(field.Name(), tag)
			if jsonName == "-" {
				continue
			}
			fieldType, err := g.typeRef(field.Type(), namespace)
			if err != nil {
				return "", err
			}
			buf.WriteString(fmt.Sprintf("    %s: %s\n", tsPropertyName(jsonName), fieldType))
			wroteField = true
		}
		if !wroteField {
			buf.WriteString("}\n")
			return strings.TrimSuffix(buf.String(), "\n"), nil
		}
		buf.WriteString("}")
		return buf.String(), nil
	default:
		ref, err := g.typeRef(underlying, namespace)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("export type %s = %s", name, ref), nil
	}
}

func (g *tsGenerator) inlineStructType(strct *types.Struct, currentNamespace string) (string, error) {
	var lines []string
	for i := 0; i < strct.NumFields(); i++ {
		field := strct.Field(i)
		if !field.Exported() {
			continue
		}
		tag := strct.Tag(i)
		jsonName := jsonFieldName(field.Name(), tag)
		if jsonName == "-" {
			continue
		}
		fieldType, err := g.typeRef(field.Type(), currentNamespace)
		if err != nil {
			return "", err
		}
		lines = append(lines, fmt.Sprintf("%s: %s", tsPropertyName(jsonName), fieldType))
	}
	if len(lines) == 0 {
		return "{}", nil
	}
	var buf bytes.Buffer
	buf.WriteString("{\n")
	for _, line := range lines {
		buf.WriteString("    " + line + "\n")
	}
	buf.WriteString("}")
	return buf.String(), nil
}

func renderPathExpression(path string) string {
	var buf bytes.Buffer
	buf.WriteByte('`')
	parts := strings.Split(strings.TrimPrefix(path, "/"), "/")
	for _, part := range parts {
		if part == "" {
			continue
		}
		buf.WriteByte('/')
		switch part[0] {
		case ':':
			name := part[1:]
			buf.WriteString("${encodeURIComponent(String(" + name + "))}")
		case '*':
			name := part[1:]
			buf.WriteString("${encodePathWildcard(String(" + name + "))}")
		default:
			buf.WriteString(part)
		}
	}
	if buf.Len() == 1 {
		buf.WriteByte('/')
	}
	buf.WriteByte('`')
	return buf.String()
}

func preferredHTTPMethod(methods []string) string {
	for _, method := range methods {
		if method == "GET" {
			return "GET"
		}
	}
	if len(methods) > 0 {
		return methods[0]
	}
	return "POST"
}

func queryDefaultMethod(method string) bool {
	switch method {
	case "GET", "HEAD", "DELETE":
		return true
	default:
		return false
	}
}

func tsTypeForParamKind(kind runtimeapi.ParamKind) string {
	switch kind {
	case runtimeapi.ParamBool:
		return "boolean"
	case runtimeapi.ParamString:
		return "string"
	default:
		return "number"
	}
}

func extractRequestFields(typ types.Type, queryDefault bool) ([]requestField, bool) {
	strct, ok := derefStruct(typ)
	if !ok {
		return nil, false
	}
	fields := make([]requestField, 0, strct.NumFields())
	for i := 0; i < strct.NumFields(); i++ {
		field := strct.Field(i)
		if !field.Exported() {
			continue
		}
		tag := strct.Tag(i)
		jsonName := jsonFieldName(field.Name(), tag)
		if header, ok := lookupTag(tag, "header"); ok && header != "" {
			fields = append(fields, requestField{Name: requestFieldName(field.Name(), tag), JSONName: jsonName, Type: field.Type(), Location: requestFieldHeader, Target: header})
			continue
		}
		if query, ok := lookupTag(tag, "query"); ok && query != "" {
			fields = append(fields, requestField{Name: requestFieldName(field.Name(), tag), JSONName: jsonName, Type: field.Type(), Location: requestFieldQuery, Target: query})
			continue
		}
		if query, ok := lookupTag(tag, "qs"); ok && query != "" {
			fields = append(fields, requestField{Name: requestFieldName(field.Name(), tag), JSONName: jsonName, Type: field.Type(), Location: requestFieldQuery, Target: query})
			continue
		}
		if cookie, ok := lookupTag(tag, "cookie"); ok && cookie != "" {
			fields = append(fields, requestField{Name: requestFieldName(field.Name(), tag), JSONName: jsonName, Type: field.Type(), Location: requestFieldCookie, Target: cookie})
			continue
		}
		if jsonName == "-" {
			continue
		}
		location := requestFieldBody
		target := jsonName
		if queryDefault {
			location = requestFieldQuery
		}
		fields = append(fields, requestField{Name: requestFieldName(field.Name(), tag), JSONName: jsonName, Type: field.Type(), Location: location, Target: target})
	}
	return fields, true
}

func canPassPayloadAsJSON(fields []requestField) bool {
	for _, field := range fields {
		if field.Location != requestFieldBody {
			return false
		}
		if field.Target != field.JSONName || field.Target != jsonFieldName(field.Name, "") {
			return false
		}
	}
	return true
}

func renderCallOptions(hasQuery, hasHeaders bool) string {
	switch {
	case hasQuery && hasHeaders:
		return "{ query, headers }"
	case hasQuery:
		return "{ query }"
	case hasHeaders:
		return "{ headers }"
	default:
		return ""
	}
}

func renderTypedEndpointCall(ep *model.Endpoint, methodName, pathExpr, jsonBodyExpr, optionsExpr string, hasPayload bool) string {
	wireInfo := wiremodel.Endpoint(ep)
	pathParams := "{}"
	if len(ep.PathParams) > 0 {
		parts := make([]string, 0, len(ep.PathParams))
		for _, param := range ep.PathParams {
			parts = append(parts, fmt.Sprintf("%s: %s", tsPropertyName(param.Name), param.Name))
		}
		pathParams = "{ " + strings.Join(parts, ", ") + " }"
	}
	payloadExpr := "undefined"
	if hasPayload {
		payloadExpr = "params"
	}
	if jsonBodyExpr == "" {
		jsonBodyExpr = "undefined"
	}
	fields := []string{
		fmt.Sprintf("endpointID: %q", wireInfo.ID),
		fmt.Sprintf("schemaHash: %q", wireInfo.SchemaHash),
		fmt.Sprintf("binaryAvailable: %t", wireInfo.Available),
		fmt.Sprintf("safeJSONRetry: %t", wireInfo.SafeJSONRetry),
		fmt.Sprintf("method: %q", methodName),
		"path: " + pathExpr,
		"pathParams: " + pathParams,
		"payload: " + payloadExpr,
		"jsonBody: " + jsonBodyExpr,
	}
	if optionsExpr != "" {
		fields = append(fields, "params: "+optionsExpr)
	}
	return "const resp = await this.baseClient.callTypedEndpoint({ " + strings.Join(fields, ", ") + " })"
}

func methodNameFromRendered(method string) string {
	method = strings.TrimSpace(method)
	method = strings.TrimPrefix(method, "public async ")
	name, _, _ := strings.Cut(method, "(")
	return strings.TrimSpace(name)
}

func namespaceForNamed(obj *types.TypeName) string {
	if obj == nil || obj.Pkg() == nil {
		return "types"
	}
	return obj.Pkg().Name()
}

func namedTypeID(named *types.Named) string {
	if obj := named.Obj(); obj != nil && obj.Pkg() != nil {
		return obj.Pkg().Path() + "." + obj.Name()
	}
	return named.String()
}

func specialTypeRef(named *types.Named) (string, bool) {
	obj := named.Obj()
	if obj == nil || obj.Pkg() == nil {
		return "", false
	}
	switch obj.Pkg().Path() {
	case "time":
		if obj.Name() == "Time" {
			return "string", true
		}
	case "encoding/json":
		if obj.Name() == "RawMessage" || obj.Name() == "Number" {
			return "JSONValue", true
		}
	}
	return "", false
}

func tsPrimitive(basic *types.Basic) string {
	switch basic.Kind() {
	case types.Bool:
		return "boolean"
	case types.String:
		return "string"
	case types.Int, types.Int8, types.Int16, types.Int32, types.Int64,
		types.Uint, types.Uint8, types.Uint16, types.Uint32, types.Uint64,
		types.Float32, types.Float64:
		return "number"
	default:
		return "JSONValue"
	}
}

func isByteSlice(slice *types.Slice) bool {
	basic, ok := slice.Elem().(*types.Basic)
	return ok && basic.Kind() == types.Byte
}

func derefStruct(typ types.Type) (*types.Struct, bool) {
	for {
		switch value := typ.(type) {
		case *types.Pointer:
			typ = value.Elem()
		case *types.Named:
			if special, ok := specialTypeRef(value); ok && special != "" {
				return nil, false
			}
			typ = value.Underlying()
		case *types.Alias:
			typ = types.Unalias(value)
		case *types.Struct:
			return value, true
		default:
			return nil, false
		}
	}
}

func lookupTag(tag, key string) (string, bool) {
	return reflect.StructTag(tag).Lookup(key)
}

func jsonFieldName(name, tag string) string {
	if raw, ok := lookupTag(tag, "json"); ok {
		parts := strings.Split(raw, ",")
		if len(parts) > 0 && parts[0] != "" {
			return parts[0]
		}
	}
	return name
}

func requestFieldName(name, tag string) string {
	if raw, ok := lookupTag(tag, "json"); ok {
		parts := strings.Split(raw, ",")
		if len(parts) > 0 && parts[0] != "" && parts[0] != "-" {
			return parts[0]
		}
	}
	return name
}

func rawPathParamNames(path string) []string {
	parts := strings.Split(strings.TrimPrefix(path, "/"), "/")
	names := make([]string, 0, len(parts))
	for _, part := range parts {
		if part == "" {
			continue
		}
		switch part[0] {
		case ':', '*':
			name := strings.TrimSpace(part[1:])
			if name != "" {
				names = append(names, name)
			}
		}
	}
	return names
}

func tsPropertyName(name string) string {
	if tsIdentifier.MatchString(name) {
		return name
	}
	return strconv.Quote(name)
}

func indentBlock(value string, depth int) string {
	prefix := strings.Repeat("    ", depth)
	lines := strings.Split(value, "\n")
	for i, line := range lines {
		lines[i] = prefix + line
	}
	return strings.Join(lines, "\n")
}

func namespaceNamesWithMethods(namespaces map[string]*tsNamespace) []string {
	names := make([]string, 0, len(namespaces))
	for name, ns := range namespaces {
		if len(ns.methods) == 0 {
			continue
		}
		names = append(names, name)
	}
	return names
}
