version: 2

project_name: onlava

builds:
  - id: onlava
    main: ./cmd/onlava
    binary: onlava
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - >-
        -s -w
        -X main.onlavaVersion={{ .Version }}
        -X main.onlavaCommit={{ .Commit }}
        -X main.onlavaBuiltAt={{ .Date }}
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - id: onlava
    ids:
      - onlava
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: checksums.txt

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^tests:"
      - "^ci:"
      - "^chore:"

release:
  github:
    owner: pbrazdil
    name: onlava
