package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"

	"github.com/pbrazdil/onlava/internal/toolchain"
)

func main() {
	repoRoot, err := findRepoRoot()
	if err != nil {
		fatal(err)
	}
	manifestPath := filepath.Join(repoRoot, "onlava.toolchain.json")
	data, err := os.ReadFile(manifestPath)
	if err != nil {
		fatal(fmt.Errorf("read %s: %w", manifestPath, err))
	}
	if _, err := toolchain.ParseManifest(data); err != nil {
		fatal(err)
	}
	var out bytes.Buffer
	out.WriteString("// Code generated by go generate ./internal/toolchain; DO NOT EDIT.\n")
	out.WriteString("package toolchain\n\n")
	fmt.Fprintf(&out, "var bundledManifestBytes = []byte(%q)\n", data)
	formatted, err := format.Source(out.Bytes())
	if err != nil {
		fatal(err)
	}
	target := filepath.Join(repoRoot, "internal", "toolchain", "manifest_gen.go")
	if err := os.WriteFile(target, formatted, 0o644); err != nil {
		fatal(fmt.Errorf("write %s: %w", target, err))
	}
}

func findRepoRoot() (string, error) {
	wd, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for dir := wd; ; dir = filepath.Dir(dir) {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			if _, err := os.Stat(filepath.Join(dir, "onlava.toolchain.json")); err == nil {
				return dir, nil
			}
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("could not find onlava repo root from %s", wd)
		}
	}
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, "gentoolchain:", err)
	os.Exit(1)
}
